name: Validate Changes

on:
  pull_request:
    branches:
      - dev

jobs:
  validate:
    name: Validate Salesforce Metadata
    runs-on: ubuntu-latest
    container: 
      image: salesforce/cli:latest-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Authenticate to Dev Sandbox (for validation)
        continue-on-error: true
        run: |
          echo ${{ secrets.SF_DEV_SFDX_URL }} | sf org login sfdx-url -s -u
      - name: Set Email Service runAsUser for Dev
        run: |
          sed -i 's/bohdan\.pyrih@everrest\.org<\/runAsUser>/bohdan.pyrih@everrest.org.dev<\/runAsUser>/' "force-app/main/default/emailservices/Work Order Service.xml-meta.xml"
      - name: Validate with tests
        run: |
          sf project deploy validate -d force-app -l RunLocalTests -w 30
      - name: Logout from Dev Sandbox
        run: |
          sfdx auth:logout --all --noprompt
