name: Validate Changes

on:
  pull_request:
    branches:
      - master

jobs:
  validate:
    name: Validate Salesforce Metadata
    runs-on: ubuntu-latest
    container: 
      image: salesforce/cli:latest-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Authenticate to Production (for validation)
        continue-on-error: true
        run: |
          echo ${{ secrets.SF_PROD_SFDX_URL }} | sf org login sfdx-url -s -u
      - name: Validate with tests
        run: |
          sf project deploy validate -d force-app -l RunLocalTests -w 30
      - name: Logout from Production
        run: |
          sfdx auth:logout --all --noprompt
